# AutoSDA Test

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Main-Script-Test" data-toc-modified-id="Main-Script-Test-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Main Script Test</a></span><ul class="toc-item"><li><span><a href="#main_design.py" data-toc-modified-id="main_design.py-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>main_design.py</a></span></li><li><span><a href="#main_program.py" data-toc-modified-id="main_program.py-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>main_program.py</a></span></li></ul></li><li><span><a href="#Function-Test" data-toc-modified-id="Function-Test-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Function Test</a></span><ul class="toc-item"><li><span><a href="#building_information.py" data-toc-modified-id="building_information.py-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>building_information.py</a></span><ul class="toc-item"><li><span><a href="#basic-information" data-toc-modified-id="basic-information-2.1.1"><span class="toc-item-num">2.1.1&nbsp;&nbsp;</span>basic information</a></span></li><li><span><a href="#define-directory" data-toc-modified-id="define-directory-2.1.2"><span class="toc-item-num">2.1.2&nbsp;&nbsp;</span>define directory</a></span></li></ul></li><li><span><a href="#global_variables.py" data-toc-modified-id="global_variables.py-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>global_variables.py</a></span><ul class="toc-item"><li><span><a href="#SteelMaterial" data-toc-modified-id="SteelMaterial-2.2.1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span>SteelMaterial</a></span></li><li><span><a href="#base_directory" data-toc-modified-id="base_directory-2.2.2"><span class="toc-item-num">2.2.2&nbsp;&nbsp;</span>base_directory</a></span></li></ul></li><li><span><a href="#help_functions.py" data-toc-modified-id="help_functions.py-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>help_functions.py</a></span></li><li><span><a href="#seismic_design.py" data-toc-modified-id="seismic_design.py-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>seismic_design.py</a></span></li></ul></li></ul></div>

## Main Script Test

### main_design.py

In [34]:
# This file is the main file that calls function to perform seismic design
# Users need to specify the system argument in this file.
# Users also need to specify the variables in "global_variables.py"

# The reason why I create this "redundant" file is to perform seismic
# design for a bunch of buildings (not a single one)

##########################################################################
#                       Relevant Publications                            #
##########################################################################

# Add relevant publications below

##########################################################################
#                       Load Necessary Packages                          #
##########################################################################

import sys
import time

from seismic_design import seismic_design
from global_variables import base_directory

# Count the starting time of the main program
start_time = time.time()

# ********************* Revised for Using System Argument ****************
# start_id = sys.argv[1]
# end_id = sys.argv[2]
# step_id = sys.argv[3]
# for id in range(int(start_id), int(end_id), int(step_id)):
#     building_id = 'Building_' + str(id)
#     print("Design for building ID = ", building_id)
#     seismic_design(building_id, base_directory)
# ********************* Revision Ends Here *******************************

# ********************* Single Building Case Ends Here *******************
IDs = [1]
for id in IDs:
    building_id = 'Building_' + str(id)
    print("Design for Building ID = ", building_id)
    seismic_design(building_id, base_directory)

# ********************* Single Building Case Ends Here *******************

end_time = time.time()

print("Running time is: %s seconds" % round(end_time - start_time, 2))

Design for Building ID =  Building_1
Member size after optimization 0
Exterior column: ['W14X730', 'W14X730', 'W14X730']
Interior column: ['W14X730', 'W14X730', 'W14X730']
Beam: ['W33X263', 'W33X263', 'W33X263']
Current story drifts: (%)
[[0.69942235]
 [0.94686735]
 [0.6398601 ]]
Member size after optimization 1
Exterior column: ['W14X730', 'W14X730', 'W14X550']
Interior column: ['W14X730', 'W14X730', 'W14X665']
Beam: ['W33X263', 'W33X263', 'W33X241']
Current story drifts: (%)
[[0.69386845]
 [0.9453125 ]
 [0.69062565]]
Member size after optimization 2
Exterior column: ['W14X730', 'W14X730', 'W14X500']
Interior column: ['W14X730', 'W14X730', 'W14X605']
Beam: ['W33X263', 'W33X263', 'W30X235']
Current story drifts: (%)
[[0.68764905]
 [0.9421544 ]
 [0.7482398 ]]
Member size after optimization 3
Exterior column: ['W14X550', 'W14X730', 'W14X500']
Interior column: ['W14X665', 'W14X730', 'W14X605']
Beam: ['W33X241', 'W33X263', 'W30X235']
Current story drifts: (%)
[[0.78373515]
 [0.94754495]
 [

### main_program.py 

In [1]:
# This file is the main file that calls function to perform seismic design, nonlinear model generation and analysis

##########################################################################
#                       Relevant Publications                            #
##########################################################################

# Add relevant publications below
# [1]. Guan, X., Burton, H., and Thomas, S. (2020).
# “Python-based computational platform to automate seismic design,
# nonlinear structural model construction and analysis of steel moment
# resisting frames.” Engineering Structures. (Under Review)

import sys
import time
import os
import pickle

from seismic_design import seismic_design
from global_variables import base_directory

from global_variables import base_directory
from global_variables import SECTION_DATABASE
from global_variables import COLUMN_DATABASE
from global_variables import BEAM_DATABASE
from model_generation import model_generation

# Count the starting time of the main program
start_time = time.time()

# *********************** Design Starts Here *************************
IDs = [0]
for id in IDs:
    building_id = 'Building_' + str(id)
    print("Design for Building ID = ", id)
    seismic_design(building_id, base_directory)
    # ******************* Nonlinear Model Generation Starts Here ******
    print("Model generation for Building ID = ", id)
    model_generation(building_id, base_directory)
    # ******************* Perform Eigen Value Analysis ****************
    print("Eigen Value Analysis for Building ID = ", id)
    analysis_type = 'EigenValueAnalysis'
    target_model = base_directory / 'BuildingNonlinearModels' / building_id / analysis_type
    os.chdir(target_model)
    os.system('OpenSees Model.tcl')
    # ******************* Perform Nonlinear Pushover Analysis *********
    print("Pushover Analysis for Building ID = ", id)
    analysis_type = 'PushoverAnalysis'
    target_model = base_directory / 'BuildingNonlinearModels' / building_id / analysis_type
    os.chdir(target_model)
    os.system('OpenSees Model.tcl')

print("The design, model construction, and analysis for Building ID = %i has been accomplished." % id)

end_time = time.time()
print("Running time is: %s seconds" % round(end_time - start_time, 2))

Design for Building ID =  0
Member size after optimization 0
Exterior column: ['W14X730', 'W14X730', 'W14X730']
Interior column: ['W14X730', 'W14X730', 'W14X730']
Beam: ['W33X263', 'W33X263', 'W33X263']
Current story drifts: (%)
[[0.69942235]
 [0.94686735]
 [0.6398601 ]]
Member size after optimization 1
Exterior column: ['W14X730', 'W14X730', 'W14X550']
Interior column: ['W14X730', 'W14X730', 'W14X665']
Beam: ['W33X263', 'W33X263', 'W33X241']
Current story drifts: (%)
[[0.69386845]
 [0.9453125 ]
 [0.69062565]]
Member size after optimization 2
Exterior column: ['W14X730', 'W14X730', 'W14X500']
Interior column: ['W14X730', 'W14X730', 'W14X605']
Beam: ['W33X263', 'W33X263', 'W30X235']
Current story drifts: (%)
[[0.68764905]
 [0.9421544 ]
 [0.7482398 ]]
Member size after optimization 3
Exterior column: ['W14X550', 'W14X730', 'W14X500']
Interior column: ['W14X665', 'W14X730', 'W14X605']
Beam: ['W33X241', 'W33X263', 'W30X235']
Current story drifts: (%)
[[0.78373515]
 [0.94754495]
 [0.7233743

## Function Test

### building_information.py 
```python
class Building(object):
    """
    This class aims to read all the relevant building information from .csv files
    It includes the following methods:
    (1) Define paths to different folders which will be used later
    (2) Read geometry information
    (3) Read load information
    (4) Read equivalent lateral force parameters
    (5) Compute lateral force for the building based on ASCE 7-10
    (6) Determine possible section sizes for columns and beams based on user-specified section depth
    (7) Propose initial beam and column sizes
    """
```

In [46]:
building_id = 'Building_0'
from global_variables import base_directory

from building_information import Building
building_1 = Building(building_id, base_directory)

#### basic information

In [50]:
building_1.UID

'Building_0'

In [51]:
building_1.base_directory

WindowsPath('G:/My Drive/Reference/GitHub/AutoSDAPlatform')

#### define directory
(1) Define paths to different folders which will be used later

```python
    def define_directory(self):
        # Define all useful paths based on the building UID and path to root folder
        # Define path to folder where the baseline .tcl files for elastic analysis are saved
        baseline_elastic_directory = self.base_directory / 'BaselineTclFiles' / 'ElasticAnalysis'
        # Define path to folder where the baseline .tcl files for nonlinear analysis are stored
        baseline_nonlinear_directory = self.base_directory / 'BaselineTclFiles' / 'NonlinearAnalysis'
        # Define path to folder where the building data (.csv) are saved
        building_data_directory = self.base_directory / 'BuildingData' / self.UID
        # Define path to folder where the generated elastic analysis OpenSees model is saved
        building_elastic_model_directory = self.base_directory / 'BuildingElasticModels' / self.UID
        # Define path to folder where the generated nonlinear analysis OpenSees model is saved
        building_nonlinear_model_directory = self.base_directory / 'BuildingNonlinearModels' / self.UID
        # Store all necessary directories into a dictionary
        self.directory = {'baseline files elastic': baseline_elastic_directory,
                          'baseline files nonlinear': baseline_nonlinear_directory,
                          'building data': building_data_directory,
                          'building elastic model': building_elastic_model_directory,
                          'building nonlinear model': building_nonlinear_model_directory}
```

In [52]:
building_1.directory

{'baseline files elastic': WindowsPath('G:/My Drive/Reference/GitHub/AutoSDAPlatform/BaselineTclFiles/ElasticAnalysis'),
 'baseline files nonlinear': WindowsPath('G:/My Drive/Reference/GitHub/AutoSDAPlatform/BaselineTclFiles/NonlinearAnalysis'),
 'building data': WindowsPath('G:/My Drive/Reference/GitHub/AutoSDAPlatform/BuildingData/Building_0'),
 'building elastic model': WindowsPath('G:/My Drive/Reference/GitHub/AutoSDAPlatform/BuildingElasticModels/Building_0'),
 'building nonlinear model': WindowsPath('G:/My Drive/Reference/GitHub/AutoSDAPlatform/BuildingNonlinearModels/Building_0')}

### global_variables.py

#### SteelMaterial

https://github.com/shishitao/AutoSDAPlatform/blob/master/steel_material.py

```python
class SteelMaterial(object):
    """
    This class is used to define the steel material.
    It includes the following physical quantities:
    (1) Yield stress (Fy)
    (2) Ultimate stress (Fu)
    (3) Young's modulus (E)
    (4) Ry value
    """

    def __init__(self, yield_stress=50, ultimate_stress=65, elastic_modulus=29000, Ry_value=1.1):
        """
        :param yield_stress: Fy of steel material, default value is 50 ksi
        :param elastic_modulus: E of steel material, default value is 29000 ksi
        """
        self.Fy = yield_stress
        self.Fu = ultimate_stress
        self.E = elastic_modulus
        self.Ry = Ry_value
```

In [ ]:
from steel_material import SteelMaterial

# Define the current utilized steel type:
steel = SteelMaterial(yield_stress=50, ultimate_stress=65, elastic_modulus=29000, Ry_value=1.1)  # Unit: ksi

In [ ]:
steel.Fy

In [ ]:
steel.Fu

In [ ]:
steel.E

In [ ]:
steel.Ry

#### base_directory
```python
# Define path to where ElasticAnalysis tool base directory
base_directory = pathlib.Path(os.getcwd())
```

In [35]:
import os
import pathlib

pathlib.Path(os.getcwd())

WindowsPath('G:/My Drive/Reference/GitHub/AutoSDAPlatform')

In [40]:
os.getcwd() # pathlib.Path(os.getcwd()) vs os.getcwd()

'G:\\My Drive\\Reference\\GitHub\\AutoSDAPlatform'

### help_functions.py

In [26]:
import numpy as np
import re
import sys

from global_variables import SECTION_DATABASE

### seismic_design.py

In [25]:
Building(building_id, base_directory)

NameError: name 'Building' is not defined