# AutoSDA Test

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Main-Script-Test" data-toc-modified-id="Main-Script-Test-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Main Script Test</a></span><ul class="toc-item"><li><span><a href="#main_design.py" data-toc-modified-id="main_design.py-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>main_design.py</a></span></li><li><span><a href="#main_program.py" data-toc-modified-id="main_program.py-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>main_program.py</a></span></li></ul></li><li><span><a href="#Function-Test" data-toc-modified-id="Function-Test-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Function Test</a></span><ul class="toc-item"><li><span><a href="#building_information.py" data-toc-modified-id="building_information.py-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>building_information.py</a></span><ul class="toc-item"><li><span><a href="#init" data-toc-modified-id="init-2.1.1"><span class="toc-item-num">2.1.1&nbsp;&nbsp;</span><strong>init</strong></a></span></li><li><span><a href="#define-directory" data-toc-modified-id="define-directory-2.1.2"><span class="toc-item-num">2.1.2&nbsp;&nbsp;</span>define directory</a></span></li><li><span><a href="#read_geometry" data-toc-modified-id="read_geometry-2.1.3"><span class="toc-item-num">2.1.3&nbsp;&nbsp;</span>read_geometry</a></span></li><li><span><a href="#read_gravity_loads" data-toc-modified-id="read_gravity_loads-2.1.4"><span class="toc-item-num">2.1.4&nbsp;&nbsp;</span>read_gravity_loads</a></span></li><li><span><a href="#read_elf_parameters" data-toc-modified-id="read_elf_parameters-2.1.5"><span class="toc-item-num">2.1.5&nbsp;&nbsp;</span>read_elf_parameters</a></span></li><li><span><a href="#compute_seismic_force" data-toc-modified-id="compute_seismic_force-2.1.6"><span class="toc-item-num">2.1.6&nbsp;&nbsp;</span>compute_seismic_force</a></span></li><li><span><a href="#determine_member_candidate" data-toc-modified-id="determine_member_candidate-2.1.7"><span class="toc-item-num">2.1.7&nbsp;&nbsp;</span>determine_member_candidate</a></span></li><li><span><a href="#initialize_member" data-toc-modified-id="initialize_member-2.1.8"><span class="toc-item-num">2.1.8&nbsp;&nbsp;</span>initialize_member</a></span></li><li><span><a href="#read_modal_period" data-toc-modified-id="read_modal_period-2.1.9"><span class="toc-item-num">2.1.9&nbsp;&nbsp;</span>read_modal_period</a></span></li><li><span><a href="#read_story_drift" data-toc-modified-id="read_story_drift-2.1.10"><span class="toc-item-num">2.1.10&nbsp;&nbsp;</span>read_story_drift</a></span></li><li><span><a href="#optimize_member_for_drift" data-toc-modified-id="optimize_member_for_drift-2.1.11"><span class="toc-item-num">2.1.11&nbsp;&nbsp;</span>optimize_member_for_drift</a></span></li><li><span><a href="#upscale_column" data-toc-modified-id="upscale_column-2.1.12"><span class="toc-item-num">2.1.12&nbsp;&nbsp;</span>upscale_column</a></span></li><li><span><a href="#upscale_beam" data-toc-modified-id="upscale_beam-2.1.13"><span class="toc-item-num">2.1.13&nbsp;&nbsp;</span>upscale_beam</a></span></li><li><span><a href="#constructability_beam" data-toc-modified-id="constructability_beam-2.1.14"><span class="toc-item-num">2.1.14&nbsp;&nbsp;</span>constructability_beam</a></span></li><li><span><a href="#constructability_column" data-toc-modified-id="constructability_column-2.1.15"><span class="toc-item-num">2.1.15&nbsp;&nbsp;</span>constructability_column</a></span></li></ul></li><li><span><a href="#elastic_analysis.py" data-toc-modified-id="elastic_analysis.py-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>elastic_analysis.py</a></span><ul class="toc-item"><li><span><a href="#write_nodes" data-toc-modified-id="write_nodes-2.2.1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span>write_nodes</a></span></li><li><span><a href="#write_fixities" data-toc-modified-id="write_fixities-2.2.2"><span class="toc-item-num">2.2.2&nbsp;&nbsp;</span>write_fixities</a></span></li><li><span><a href="#write_floor_constraint" data-toc-modified-id="write_floor_constraint-2.2.3"><span class="toc-item-num">2.2.3&nbsp;&nbsp;</span>write_floor_constraint</a></span></li><li><span><a href="#write_beam" data-toc-modified-id="write_beam-2.2.4"><span class="toc-item-num">2.2.4&nbsp;&nbsp;</span>write_beam</a></span></li></ul></li><li><span><a href="#global_variables.py" data-toc-modified-id="global_variables.py-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>global_variables.py</a></span><ul class="toc-item"><li><span><a href="#SteelMaterial" data-toc-modified-id="SteelMaterial-2.3.1"><span class="toc-item-num">2.3.1&nbsp;&nbsp;</span>SteelMaterial</a></span></li><li><span><a href="#base_directory" data-toc-modified-id="base_directory-2.3.2"><span class="toc-item-num">2.3.2&nbsp;&nbsp;</span>base_directory</a></span></li></ul></li><li><span><a href="#help_functions.py" data-toc-modified-id="help_functions.py-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>help_functions.py</a></span><ul class="toc-item"><li><span><a href="#" data-toc-modified-id="-2.4.1"><span class="toc-item-num">2.4.1&nbsp;&nbsp;</span></a></span></li></ul></li><li><span><a href="#seismic_design.py" data-toc-modified-id="seismic_design.py-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>seismic_design.py</a></span><ul class="toc-item"><li><span><a href="#seismic_force" data-toc-modified-id="seismic_force-2.5.1"><span class="toc-item-num">2.5.1&nbsp;&nbsp;</span>seismic_force</a></span></li></ul></li></ul></li></ul></div>

## Main Script Test

### main_design.py

In [60]:
# This file is the main file that calls function to perform seismic design
# Users need to specify the system argument in this file.
# Users also need to specify the variables in "global_variables.py"

# The reason why I create this "redundant" file is to perform seismic
# design for a bunch of buildings (not a single one)

##########################################################################
#                       Relevant Publications                            #
##########################################################################

# Add relevant publications below

##########################################################################
#                       Load Necessary Packages                          #
##########################################################################

import sys
import time

from seismic_design import seismic_design
from global_variables import base_directory

# Count the starting time of the main program
start_time = time.time()

# ********************* Revised for Using System Argument ****************
# start_id = sys.argv[1]
# end_id = sys.argv[2]
# step_id = sys.argv[3]
# for id in range(int(start_id), int(end_id), int(step_id)):
#     building_id = 'Building_' + str(id)
#     print("Design for building ID = ", building_id)
#     seismic_design(building_id, base_directory)
# ********************* Revision Ends Here *******************************

# ********************* Single Building Case Ends Here *******************
IDs = [0, 3]
for id in IDs:
    building_id = 'Building_' + str(id)
    print("Design for Building ID = ", building_id)
    seismic_design(building_id, base_directory)

# ********************* Single Building Case Ends Here *******************

end_time = time.time()

print("Running time is: %s seconds" % round(end_time - start_time, 2))

Design for Building ID =  Building_0
Member size after optimization 0
Exterior column: ['W14X730', 'W14X730', 'W14X730']
Interior column: ['W14X730', 'W14X730', 'W14X730']
Beam: ['W33X263', 'W33X263', 'W33X263']
Current story drifts: (%)
[[0.69942235]
 [0.94686735]
 [0.6398601 ]]
Member size after optimization 1
Exterior column: ['W14X730', 'W14X730', 'W14X550']
Interior column: ['W14X730', 'W14X730', 'W14X665']
Beam: ['W33X263', 'W33X263', 'W33X241']
Current story drifts: (%)
[[0.69386845]
 [0.9453125 ]
 [0.69062565]]
Member size after optimization 2
Exterior column: ['W14X730', 'W14X730', 'W14X500']
Interior column: ['W14X730', 'W14X730', 'W14X605']
Beam: ['W33X263', 'W33X263', 'W30X235']
Current story drifts: (%)
[[0.68764905]
 [0.9421544 ]
 [0.7482398 ]]
Member size after optimization 3
Exterior column: ['W14X550', 'W14X730', 'W14X500']
Interior column: ['W14X665', 'W14X730', 'W14X605']
Beam: ['W33X241', 'W33X263', 'W30X235']
Current story drifts: (%)
[[0.78373515]
 [0.94754495]
 [

Member size after optimization 1
Exterior column: ['W14X730', 'W14X730', 'W14X550']
Interior column: ['W14X730', 'W14X730', 'W14X665']
Beam: ['W33X263', 'W33X263', 'W33X241']
Current story drifts: (%)
[[0.69386845]
 [0.9453125 ]
 [0.69062565]]
Member size after optimization 2
Exterior column: ['W14X730', 'W14X730', 'W14X500']
Interior column: ['W14X730', 'W14X730', 'W14X605']
Beam: ['W33X263', 'W33X263', 'W30X235']
Current story drifts: (%)
[[0.68764905]
 [0.9421544 ]
 [0.7482398 ]]
Member size after optimization 3
Exterior column: ['W14X550', 'W14X730', 'W14X500']
Interior column: ['W14X665', 'W14X730', 'W14X605']
Beam: ['W33X241', 'W33X263', 'W30X235']
Current story drifts: (%)
[[0.78373515]
 [0.94754495]
 [0.7233743 ]]
Member size after optimization 4
Exterior column: ['W14X550', 'W14X730', 'W14X455']
Interior column: ['W14X665', 'W14X730', 'W14X550']
Beam: ['W33X241', 'W33X263', 'W27X217']
Current story drifts: (%)
[[0.7753196]
 [0.9434733]
 [0.7985395]]
Member size after optimizat

### main_program.py 

In [2]:
# This file is the main file that calls function to perform seismic design, nonlinear model generation and analysis

##########################################################################
#                       Relevant Publications                            #
##########################################################################

# Add relevant publications below
# [1]. Guan, X., Burton, H., and Thomas, S. (2020).
# “Python-based computational platform to automate seismic design,
# nonlinear structural model construction and analysis of steel moment
# resisting frames.” Engineering Structures. (Under Review)

import sys
import time
import os
import pickle

from seismic_design import seismic_design
from global_variables import base_directory

from global_variables import base_directory
from global_variables import SECTION_DATABASE
from global_variables import COLUMN_DATABASE
from global_variables import BEAM_DATABASE
from model_generation import model_generation

# Count the starting time of the main program
start_time = time.time()

# *********************** Design Starts Here *************************
IDs = [0]
for id in IDs:
    building_id = 'Building_' + str(id)
    print("Design for Building ID = ", id)
    seismic_design(building_id, base_directory)
    # ******************* Nonlinear Model Generation Starts Here ******
    print("Model generation for Building ID = ", id)
    model_generation(building_id, base_directory)
    # ******************* Perform Eigen Value Analysis ****************
    print("Eigen Value Analysis for Building ID = ", id)
    analysis_type = 'EigenValueAnalysis'
    target_model = base_directory / 'BuildingNonlinearModels' / building_id / analysis_type
    os.chdir(target_model)
    os.system('OpenSees Model.tcl')
    # ******************* Perform Nonlinear Pushover Analysis *********
    print("Pushover Analysis for Building ID = ", id)
    analysis_type = 'PushoverAnalysis'
    target_model = base_directory / 'BuildingNonlinearModels' / building_id / analysis_type
    os.chdir(target_model)
    os.system('OpenSees Model.tcl')

print("The design, model construction, and analysis for Building ID = %i has been accomplished." % id)

end_time = time.time()
print("Running time is: %s seconds" % round(end_time - start_time, 2))

Design for Building ID =  0
Member size after optimization 0
Exterior column: ['W14X730', 'W14X730', 'W14X730']
Interior column: ['W14X730', 'W14X730', 'W14X730']
Beam: ['W33X263', 'W33X263', 'W33X263']
Current story drifts: (%)
[[0.69942235]
 [0.94686735]
 [0.6398601 ]]
Member size after optimization 1
Exterior column: ['W14X730', 'W14X730', 'W14X550']
Interior column: ['W14X730', 'W14X730', 'W14X665']
Beam: ['W33X263', 'W33X263', 'W33X241']
Current story drifts: (%)
[[0.69386845]
 [0.9453125 ]
 [0.69062565]]
Member size after optimization 2
Exterior column: ['W14X730', 'W14X730', 'W14X500']
Interior column: ['W14X730', 'W14X730', 'W14X605']
Beam: ['W33X263', 'W33X263', 'W30X235']
Current story drifts: (%)
[[0.68764905]
 [0.9421544 ]
 [0.7482398 ]]
Member size after optimization 3
Exterior column: ['W14X550', 'W14X730', 'W14X500']
Interior column: ['W14X665', 'W14X730', 'W14X605']
Beam: ['W33X241', 'W33X263', 'W30X235']
Current story drifts: (%)
[[0.78373515]
 [0.94754495]
 [0.7233743

The design, model construction, and analysis for Building ID = 0 has been accomplished.
Running time is: 89.31 seconds


## Function Test

### building_information.py

https://github.com/shishitao/AutoSDAPlatform/blob/master/building_information.py

```python
class Building(object):
    """
    This class aims to read all the relevant building information from .csv files
    It includes the following methods:
    (1) Define paths to different folders which will be used later
    (2) Read geometry information
    (3) Read load information
    (4) Read equivalent lateral force parameters
    (5) Compute lateral force for the building based on ASCE 7-10
    (6) Determine possible section sizes for columns and beams based on user-specified section depth
    (7) Propose initial beam and column sizes
    """
```

In [3]:
building_id = 'Building_0'
from global_variables import base_directory

from building_information import Building
building_1 = Building(building_id, base_directory)

#### __init__
```python
def __init__(self, building_id, base_directory):
    """
    This function initializes the attributes of a building instance
    :param building_id: a string that used as a UID to label the building
    :param base_directory:  a string that denotes the path to root folder
    """
    # Assign basic information: unique ID for the building and base path
    self.UID = building_id
    self.base_directory = base_directory

    # Initialize the attributes for the building instance (will be assigned values in the class methods)
    self.directory = {}
    self.geometry = {}
    self.gravity_loads = {}
    self.elf_parameters = {}
    self.seismic_force_for_strength = {}
    self.seismic_force_for_drift = {}
    self.section_depth = {}
    self.element_candidate = {}
    self.member_size = {}
    self.elastic_response = {}
    self.construction_size = {}

    # Call defined methods to achieve the goal of the class
    self.define_directory()
    self.read_geometry()
    self.read_gravity_loads()
    self.read_elf_parameters()
    # self.compute_seismic_force()
    self.determine_member_candidate()
    self.initialize_member()
    # self.initialize_member_v2()
```

In [4]:
building_1.UID

'Building_0'

In [5]:
building_1.base_directory

WindowsPath('G:/My Drive/Reference/GitHub/AutoSDAPlatform')

#### define directory
(1) Define paths to different folders which will be used later

```python
def define_directory(self):
    # Define all useful paths based on the building UID and path to root folder
    # Define path to folder where the baseline .tcl files for elastic analysis are saved
    baseline_elastic_directory = self.base_directory / 'BaselineTclFiles' / 'ElasticAnalysis'
    # Define path to folder where the baseline .tcl files for nonlinear analysis are stored
    baseline_nonlinear_directory = self.base_directory / 'BaselineTclFiles' / 'NonlinearAnalysis'
    # Define path to folder where the building data (.csv) are saved
    building_data_directory = self.base_directory / 'BuildingData' / self.UID
    # Define path to folder where the generated elastic analysis OpenSees model is saved
    building_elastic_model_directory = self.base_directory / 'BuildingElasticModels' / self.UID
    # Define path to folder where the generated nonlinear analysis OpenSees model is saved
    building_nonlinear_model_directory = self.base_directory / 'BuildingNonlinearModels' / self.UID
    # Store all necessary directories into a dictionary
    self.directory = {'baseline files elastic': baseline_elastic_directory,
                      'baseline files nonlinear': baseline_nonlinear_directory,
                      'building data': building_data_directory,
                      'building elastic model': building_elastic_model_directory,
                      'building nonlinear model': building_nonlinear_model_directory}
```

In [6]:
building_1.directory

{'baseline files elastic': WindowsPath('G:/My Drive/Reference/GitHub/AutoSDAPlatform/BaselineTclFiles/ElasticAnalysis'),
 'baseline files nonlinear': WindowsPath('G:/My Drive/Reference/GitHub/AutoSDAPlatform/BaselineTclFiles/NonlinearAnalysis'),
 'building data': WindowsPath('G:/My Drive/Reference/GitHub/AutoSDAPlatform/BuildingData/Building_0'),
 'building elastic model': WindowsPath('G:/My Drive/Reference/GitHub/AutoSDAPlatform/BuildingElasticModels/Building_0'),
 'building nonlinear model': WindowsPath('G:/My Drive/Reference/GitHub/AutoSDAPlatform/BuildingNonlinearModels/Building_0')}

In [7]:
building_1.directory['baseline files elastic']

WindowsPath('G:/My Drive/Reference/GitHub/AutoSDAPlatform/BaselineTclFiles/ElasticAnalysis')

In [8]:
building_1.directory['baseline files nonlinear']

WindowsPath('G:/My Drive/Reference/GitHub/AutoSDAPlatform/BaselineTclFiles/NonlinearAnalysis')

#### read_geometry

```python
def read_geometry(self):
    """
    This method is used to read the building geometry information from .csv files:
    (1) Change the working directory to the folder where .csv data are stored
    (2) Open the .csv file and save all relevant information to the object itself
    """
    os.chdir(self.directory['building data'])
    with open('Geometry.csv', 'r') as csvfile:
        geometry_data = pd.read_csv(csvfile, header=0)
    # Each variable is a scalar
    number_of_story = geometry_data.loc[0, 'number of story']
    number_of_X_bay = geometry_data.loc[0, 'number of X bay']
    number_of_Z_bay = geometry_data.loc[0, 'number of Z bay']
    first_story_height = geometry_data.loc[0, 'first story height']
    typical_story_height = geometry_data.loc[0, 'typical story height']
    X_bay_width = geometry_data.loc[0, 'X bay width']
    Z_bay_width = geometry_data.loc[0, 'Z bay width']
    number_of_X_LFRS = geometry_data.loc[0, 'number of X LFRS']  # number of lateral resisting frame in X direction
    number_of_Z_LFRS = geometry_data.loc[0, 'number of Z LFRS']  # number of lateral resisting frame in Z direction
    # Call function defined in "help_functions.py" to determine the height for each floor level
    floor_height = determine_floor_height(number_of_story, first_story_height, typical_story_height)
    # Store all necessary information into a dictionary named geometry
    self.geometry = {'number of story': number_of_story,
                     'number of X bay': number_of_X_bay,
                     'number of Z bay': number_of_Z_bay,
                     'first story height': first_story_height,
                     'typical story height': typical_story_height,
                     'X bay width': X_bay_width,
                     'Z bay width': Z_bay_width,
                     'number of X LFRS': number_of_X_LFRS,
                     'number of Z LFRS': number_of_Z_LFRS,
                     'floor height': floor_height}
```

In [9]:
building_1.geometry

{'number of story': 3,
 'number of X bay': 4,
 'number of Z bay': 4,
 'first story height': 13,
 'typical story height': 13,
 'X bay width': 30,
 'Z bay width': 30,
 'number of X LFRS': 2,
 'number of Z LFRS': 2,
 'floor height': array([[ 0.],
        [13.],
        [26.],
        [39.]])}

In [10]:
building_1.geometry['floor height']

array([[ 0.],
       [13.],
       [26.],
       [39.]])

#### read_gravity_loads

```python
def read_gravity_loads(self):
    """
    This method is used to read the load information from .csv files
    (1) Change the directory to the folder where the load data are stored
    (2) Read the .csv files and assign save load values to object values
    """
    os.chdir(self.directory['building data'])
    with open('Loads.csv', 'r') as csvfile:
        loads_data = pd.read_csv(csvfile, header=0)
    # All data is a list (array). Length is the number of story
    # Be cautious about the unit
    floor_weight = loads_data['floor weight']
    floor_dead_load = loads_data['floor dead load']
    floor_live_load = loads_data['floor live load']
    beam_dead_load = loads_data['beam dead load']
    beam_live_load = loads_data['beam live load']
    leaning_column_dead_load = loads_data['leaning column dead load']
    leaning_column_live_load = loads_data['leaning column live load']
    # Store all necessary information into a dictionary named gravity_loads
    self.gravity_loads = {'floor weight': floor_weight,
                          'floor dead load': floor_dead_load,
                          'floor live load': floor_live_load,
                          'beam dead load': beam_dead_load,
                          'beam live load': beam_live_load,
                          'leaning column dead load': leaning_column_dead_load,
                          'leaning column live load': leaning_column_live_load}
```

In [11]:
building_1.gravity_loads

{'floor weight': 0    2289
 1    2289
 2    2289
 Name: floor weight, dtype: int64,
 'floor dead load': 0    106
 1    106
 2    106
 Name: floor dead load, dtype: int64,
 'floor live load': 0    50
 1    50
 2    50
 Name: floor live load, dtype: int64,
 'beam dead load': 0    1590
 1    1590
 2    1590
 Name: beam dead load, dtype: int64,
 'beam live load': 0    750
 1    750
 2    750
 Name: beam live load, dtype: int64,
 'leaning column dead load': 0    954
 1    954
 2    954
 Name: leaning column dead load, dtype: int64,
 'leaning column live load': 0    450
 1    450
 2    450
 Name: leaning column live load, dtype: int64}

#### read_elf_parameters

```python
def read_elf_parameters(self):
    """
    This method is used to read equivalent lateral force (in short: elf) parameters and calculate SDS and SD1
    (1) Read equivalent lateral force parameters
    (2) Calculate SMS, SM1, SDS, SD1 values and save them into the attribute
    """
    os.chdir(self.directory['building data'])
    with open('ELFParameters.csv', 'r') as csvfile:
        elf_parameters_data = pd.read_csv(csvfile, header=0)
    # Determine Fa and Fv coefficient based on site class and Ss and S1 (ASCE 7-10 Table 11.4-1 & 11.4-2)
    # Call function defined in "help_functions.py" to calculate two coefficients: Fa and Fv
    Fa = determine_Fa_coefficient(elf_parameters_data.loc[0, 'site class'], elf_parameters_data.loc[0, 'Ss'])
    Fv = determine_Fv_coefficient(elf_parameters_data.loc[0, 'site class'], elf_parameters_data.loc[0, 'S1'])
    # Determine SMS, SM1, SDS, SD1 using the defined function in "help_functions.py"
    SMS, SM1, SDS, SD1 = calculate_DBE_acceleration(elf_parameters_data.loc[0, 'Ss'],
                                                    elf_parameters_data.loc[0, 'S1'], Fa, Fv)
    # Determine Cu using the defined function in "help_functions.py"
    Cu = determine_Cu_coefficient(SD1)
    # Calculate the building period: approximate fundamental period and upper bound period
    approximate_period = elf_parameters_data.loc[0, 'Ct'] \
                         * (self.geometry['floor height'][-1]**elf_parameters_data.loc[0, 'x'])
    upper_period = Cu * approximate_period
    # Save all coefficient into the dictionary named elf_parameters
    self.elf_parameters = {'Ss': elf_parameters_data.loc[0, 'Ss'], 'S1': elf_parameters_data.loc[0, 'S1'],
                           'TL': elf_parameters_data.loc[0, 'TL'], 'Cd': elf_parameters_data.loc[0, 'Cd'],
                           'R': elf_parameters_data.loc[0, 'R'], 'Ie': elf_parameters_data.loc[0, 'Ie'],
                           'rho': elf_parameters_data.loc[0, 'rho'],
                           'site class': elf_parameters_data.loc[0, 'site class'],
                           'Ct': elf_parameters_data.loc[0, 'Ct'], 'x': elf_parameters_data.loc[0, 'x'],
                           'Fa': Fa, 'Fv': Fv, 'SMS': SMS, 'SM1': SM1, 'SDS': SDS, 'SD1': SD1, 'Cu': Cu,
                           'approximate period': approximate_period, 'period': upper_period}
```

In [12]:
building_1.elf_parameters

{'Ss': 2.25,
 'S1': 0.6,
 'TL': 8,
 'Cd': 5.5,
 'R': 8,
 'Ie': 1,
 'rho': 1,
 'site class': 'D',
 'Ct': 0.027999999999999997,
 'x': 0.8,
 'Fa': 1.0,
 'Fv': 1.5,
 'SMS': 2.25,
 'SM1': 0.8999999999999999,
 'SDS': 1.5,
 'SD1': 0.5999999999999999,
 'Cu': 1.4,
 'approximate period': array([0.5248192]),
 'period': array([0.73474688])}

#### compute_seismic_force

```python
def compute_seismic_force(self):
    """
    This method is used to calculate the seismic story force using ELF procedure specified in ASCE 7-10 Section 12.8
    (1) Determine the floor level height and save it in a list (array)
    (2) Determine the correct period between first mode period and CuTa
    (3) Determine the Cs coefficient
    (4) Determine the lateral force at each floor level (ground to roof) and save it in an arrary
    """
    # Please note that the period for computing the required strength should be bounded by CuTa
    period_for_strength = min(self.elf_parameters['modal period'], self.elf_parameters['period'])
    # The period used for computing story drift is not required to be bounded by CuTa
    if PERIOD_FOR_DRIFT_LIMIT:
        period_for_drift = min(self.elf_parameters['modal period'], self.elf_parameters['period'])
    else:
        period_for_drift = self.elf_parameters['modal period']
    # Call function defined in "help_functions.py" to determine the seismic response coefficient
    Cs_for_strength = calculate_Cs_coefficient(self.elf_parameters['SDS'], self.elf_parameters['SD1'],
                                               self.elf_parameters['S1'], period_for_strength,
                                               self.elf_parameters['TL'], self.elf_parameters['R'],
                                               self.elf_parameters['Ie'], False)
    Cs_for_drift = calculate_Cs_coefficient(self.elf_parameters['SDS'], self.elf_parameters['SD1'],
                                            self.elf_parameters['S1'], period_for_drift,
                                            self.elf_parameters['TL'], self.elf_parameters['R'],
                                            self.elf_parameters['Ie'], True)
    # Calculate the base shear
    base_shear_for_strength = Cs_for_strength * np.sum(self.gravity_loads['floor weight'])
    base_shear_for_drift = Cs_for_drift * np.sum(self.gravity_loads['floor weight'])
    # Call function defined in "help_functions.py" to compute k coefficient
    k = determine_k_coeficient(self.elf_parameters['period'])
    # Call function defined in "help_functions.py" to determine the lateral force for each floor level
    lateral_story_force_for_strength, story_shear_for_strength \
        = calculate_seismic_force(base_shear_for_strength, self.gravity_loads['floor weight'], \
                                  self.geometry['floor height'], k)
    lateral_story_force_for_drift, story_shear_for_drift \
        = calculate_seismic_force(base_shear_for_drift, self.gravity_loads['floor weight'], \
                                  self.geometry['floor height'], k)
    # Store information into class attribute
    self.seismic_force_for_strength = {'lateral story force': lateral_story_force_for_strength, \
                                       'story shear': story_shear_for_strength, \
                                       'base shear': base_shear_for_strength, 'Cs': Cs_for_strength}
    self.seismic_force_for_drift = {'lateral story force': lateral_story_force_for_drift, \
                                       'story shear': story_shear_for_drift, \
                                       'base shear': base_shear_for_drift, 'Cs': Cs_for_drift}
```

In [13]:
building_1.seismic_force_for_strength 

{}

In [14]:
building_1.seismic_force_for_drift  

{}

In [15]:
# why this function was commented?

#### determine_member_candidate

```python
def determine_member_candidate(self):
    """
    This method is used to determine all possible member candidates based on the user-specified section depth
    :return: a dictionary which contains the all possible sizes for exterior columns, interior columns, and beams.
    """
    # Read the user-specified depths for interior columns, exterior columns, and beams.
    os.chdir(self.directory['building data'])
    with open('MemberDepth.csv', 'r') as csvfile:
        depth_data = pd.read_csv(csvfile, header=0)
    # Initialize dictionary that will be used to store all possible section sizes for each member (in each story)
    interior_column_candidate = {}
    exterior_column_candidate = {}
    beam_candidate = {}
    # Initialize list that will be used to store section depth for each member (in each story)
    interior_column_depth = []
    exterior_column_depth = []
    beam_depth = []
    for story in range(0, self.geometry['number of story']):  # story number
        # Initialize the Series that will be used to store the member sizes for each single story
        temp_interior_column = pd.Series()
        temp_exterior_column = pd.Series()
        temp_beam = pd.Series()
        # Convert string (read from csv) to list
        interior_column_depth_list = depth_data.loc[story, 'interior column'].split(', ')
        exterior_column_depth_list = depth_data.loc[story, 'exterior column'].split(', ')
        beam_depth_list = depth_data.loc[story, 'beam'].split(', ')
        # Find the section size candidates associated with a certain depth specified by user
        for item in range(0, len(interior_column_depth_list)):
            temp1 = find_section_candidate(interior_column_depth_list[item], COLUMN_DATABASE)
            temp_interior_column = pd.concat([temp_interior_column, temp1])
        for item in range(0, len(exterior_column_depth_list)):
            temp2 = find_section_candidate(exterior_column_depth_list[item], COLUMN_DATABASE)
            temp_exterior_column = pd.concat([temp_exterior_column, temp2])
        for item in range(0, len(beam_depth_list)):
            temp3 = find_section_candidate(beam_depth_list[item], BEAM_DATABASE)
            temp_beam = pd.concat([temp_beam, temp3])
        # Store the section size candidates for each member per story in a dictionary
        # Re-order the Series based on the index (which is further based on descending order of Ix for column
        # and Zx for beam). Convert Series to list.
        interior_column_candidate['story %s' % (story+1)] = list(temp_interior_column.sort_index())
        exterior_column_candidate['story %s' % (story+1)] = list(temp_exterior_column.sort_index())
        beam_candidate['floor level %s' % (story+2)] = list(temp_beam.sort_index())
        # Store the section depth for each member in each story
        interior_column_depth.append(interior_column_depth_list)
        exterior_column_depth.append(exterior_column_depth_list)
        beam_depth.append(beam_depth_list)
    # Summarize all the section candidates to a dictionary
    self.element_candidate = {'interior column': interior_column_candidate,
                              'exterior column': exterior_column_candidate,
                              'beam': beam_candidate}
    # Summarize all the section depth to a dictionary
    self.section_depth = {'interior column': interior_column_depth,
                          'exterior column': exterior_column_depth,
                          'beam': beam_depth}
```

In [16]:
building_1.section_depth

{'interior column': [['W14'], ['W14'], ['W14']],
 'exterior column': [['W14'], ['W14'], ['W14']],
 'beam': [['W27', 'W30', 'W33'], ['W27', 'W30', 'W33'], ['W27', 'W30', 'W33']]}

#### initialize_member

```python
def initialize_member(self):
    """
    This method is used to initialize the member size
    :return: a dictionary which includes the initial size for interior columns, exterior columns, and beams
    """
    # Define initial sizes for columns and beams
    interior_column = []
    exterior_column = []
    beam = []
    for story in range(0, self.geometry['number of story']):
        # The initial column is selected as the greatest sizes in the candidate pool
        initial_interior = self.element_candidate['interior column']['story %s' % (story+1)][0]
        initial_exterior = self.element_candidate['exterior column']['story %s' % (story+1)][0]
        # Merge initial size of each story together
        interior_column.append(initial_interior)
        exterior_column.append(initial_exterior)
        # Compute the section property of the interior column size
        reference_property = search_section_property(initial_interior, SECTION_DATABASE)
        # Determine the beam size based on beam-to-column section modulus ratio
        beam_size = search_member_size('Zx', reference_property['Zx']*BEAM_TO_COLUMN_RATIO,
                                       self.element_candidate['beam']['floor level %s' % (story+2)],
                                       SECTION_DATABASE)
        # Merge initial beam size of each story together
        beam.append(beam_size)
    # Store all initial member sizes into the dictionary (which will be updated using optimization algorithm later)
    self.member_size = {'interior column': interior_column,
                        'exterior column': exterior_column,
                        'beam': beam}
```

In [26]:
building_1.member_size

{'interior column': ['W14X730', 'W14X730', 'W14X730'],
 'exterior column': ['W14X730', 'W14X730', 'W14X730'],
 'beam': ['W33X263', 'W33X263', 'W33X263']}

#### read_modal_period

```python
def read_modal_period(self):
    """
    This method is used to read the modal period from OpenSees eigen value analysis results and store it in ELF
    parameters.
    :return: the first mode period stored in self.elf_parameters
    """
    # Change the working directory to the folder where the eigen value analysis results are stored
    path_modal_period = self.directory['building elastic model'] / 'EigenAnalysis'
    os.chdir(path_modal_period)
    # Save the first mode period in elf_parameters
    # period = np.loadtxt('Periods.out')
    period = pd.read_csv('Periods.out', header=None)
    self.elf_parameters['modal period'] = np.asscalar((period.iloc[0, 0]))
```

In [27]:
building_1.elf_parameters

{'Ss': 2.25,
 'S1': 0.6,
 'TL': 8,
 'Cd': 5.5,
 'R': 8,
 'Ie': 1,
 'rho': 1,
 'site class': 'D',
 'Ct': 0.027999999999999997,
 'x': 0.8,
 'Fa': 1.0,
 'Fv': 1.5,
 'SMS': 2.25,
 'SM1': 0.8999999999999999,
 'SDS': 1.5,
 'SD1': 0.5999999999999999,
 'Cu': 1.4,
 'approximate period': array([0.5248192]),
 'period': array([0.73474688])}

#### read_story_drift

```python
def read_story_drift(self):
    """
    This method is used to read the story drifts from OpenSees elastic analysis results and stored it as attribute
    The load case for story drift is the combination of dead, live, and earthquake loads.
    :return: an [story*1] array which includes the story drifts for each story.
    """
    # Change the working directory to the folder where story drifts are stored
    path_story_drift = self.directory['building elastic model'] / 'GravityEarthquake' / 'StoryDrifts'
    os.chdir(path_story_drift)
    # Save all story drifts in an array
    story_drift = np.zeros([self.geometry['number of story'], 1])
    for story in range(self.geometry['number of story']):
        file_name = 'Story' + str(story+1) + '.out'
        read_data = np.loadtxt(file_name)
        story_drift[story] = read_data[-1, -1]
    # Assign the story drifts results into class attribute
    self.elastic_response = {'story drift': story_drift}
```

In [28]:
building_1.elastic_response

{}

In [29]:
# no call

#### optimize_member_for_drift

```python
def optimize_member_for_drift(self):
    """
    This method is used to decrease the member size such that the design is most economic.
    :return: update self.member_size
    """
    # Find the story which has the smallest drift
    target_story = np.where(self.elastic_response['story drift'] ==
                            np.min(self.elastic_response['story drift']))[0][0]
    # Update the interior column size in target story
    self.member_size['interior column'][target_story] = \
        decrease_member_size(self.element_candidate['interior column']['story %s' % (target_story+1)],
                             self.member_size['interior column'][target_story])
    # Compute the section property of the interior column size
    reference_property = search_section_property(self.member_size['interior column'][target_story],
                                                 SECTION_DATABASE)
    # Determine the beam size based on beam-to-column section modulus ratio
    beam_size = search_member_size('Zx', reference_property['Zx'] * BEAM_TO_COLUMN_RATIO,
                                   self.element_candidate['beam']['floor level %s' %(target_story+2)],
                                   SECTION_DATABASE)
    # "Push" the updated beam size back to the class dictionary
    self.member_size['beam'][target_story] = beam_size
    # Determine the exterior column size based on exterior/interior column moment of inertia ratio
    exterior_size = search_member_size('Ix', reference_property['Ix'] * EXTERIOR_INTERIOR_COLUMN_RATIO,
                                       self.element_candidate['exterior column']['story %s' % (target_story+1)],
                                       SECTION_DATABASE)
    self.member_size['exterior column'][target_story] = exterior_size
```

In [30]:
building_1.member_size

{'interior column': ['W14X730', 'W14X730', 'W14X730'],
 'exterior column': ['W14X730', 'W14X730', 'W14X730'],
 'beam': ['W33X263', 'W33X263', 'W33X263']}

In [35]:
building_1.member_size['exterior column']

['W14X730', 'W14X730', 'W14X730']

#### upscale_column

```python
def upscale_column(self, target_story, type_column):
    """
    This method is used to increase  column size which might be necessary when column strength is not sufficient
    or strong column weak beam is not satisfied.
    :param target_story: a scalar to denote which story column shall be increased (from 0 to total story # - 1).
    :param type_column: a string denoting whether it is an exterior column or interior column
    :return: update the column size stored in self.member_size
    """
    temp_size = increase_member_size(self.element_candidate[type_column]['story %s' % (target_story+1)],
                                     self.member_size[type_column][target_story])
    self.member_size[type_column][target_story] = temp_size
    # temp_size_2 = increase_member_size(self.element_candidate['exterior column']['story %x' % (target_story+1)],
    #                                    self.member_size['exterior column'][target_story])
    # self.member_size['exterior column'][target_story] = temp_size_2
```

In [34]:
building_1.member_size['interior column']

['W14X730', 'W14X730', 'W14X730']

In [35]:
building_1.member_size['exterior column']

['W14X730', 'W14X730', 'W14X730']

#### upscale_beam

```python
def upscale_beam(self, target_floor):
    """
    This method is used to increase beam size which might be necessary when beam strength is not sufficient
    :param target_floor: a scalar to denote which floor beam shall be improved. (from 0 to total story # - 1)
    :return: update the beam size stored in self.member_size
    """
    temp_size = increase_member_size(self.element_candidate['beam']['floor level %s' % (target_floor+2)],
                                     self.member_size['beam'][target_floor])
    self.member_size['beam'][target_floor] = temp_size
```

In [33]:
building_1.member_size['beam']

['W33X263', 'W33X263', 'W33X263']

#### constructability_beam

```python
def constructability_beam(self):
    """
    This method is used to update the beam member size by considering the constructability (ease of construction).
    :return: update the beam sizes stored in self.member_size['beam']
    """
    # Make a deep copy of the member sizes and stored them in a new dictionary named construction_size
    # Use deep copy to avoid changing the variables stored in member size
    temp_size = copy.deepcopy(self.member_size)
    # Update beam size (beam size is updated based on descending order of Zx)
    self.construction_size['beam'] = constructability_helper(temp_size['beam'], IDENTICAL_SIZE_PER_STORY,
                                                             self.geometry['number of story'], 'Ix')
    # Column sizes here have not been updated (just directly copy)
    self.construction_size['interior column'] = temp_size['interior column']
    self.construction_size['exterior column'] = temp_size['exterior column']
```

In [37]:
building_1.construction_size

{}

In [39]:
building_1.construction_size['beam']

KeyError: 'beam'

#### constructability_column

```python
def constructability_column(self):
    """
    This method is used to update the column member size by considering the constructability (ease of construction).
    :return: update the column sizes stored in self.member_size
    """
    # Make a copy of the member size
    temp_size = copy.deepcopy(self.member_size)
    # Update column sizes based on the sorted Ix
    member_list = ['interior column', 'exterior column']
    for mem in member_list:
        self.construction_size[mem] = constructability_helper(temp_size[mem], IDENTICAL_SIZE_PER_STORY,
                                                              self.geometry['number of story'], 'Ix')
```

In [38]:
building_1.construction_size['interior column']

KeyError: 'interior column'

### elastic_analysis.py

https://github.com/shishitao/AutoSDAPlatform/blob/master/elastic_analysis.py

```python
####################################################################
#              Generate OpenSees model (write .tcl files)             ####################################################################

class ElasticAnalysis(object):
    """
    This class generates the .tcl files required for elastic analysis. It includes .tcl files for the following modules:
    (1) OpenSees nodes
    (2) boundary condition
    (3) floor constraint
    (4) beam component
    (5) column component
    (6) leaning column spring
    (7) mass
    (8) all recorders
    (9) story drift recorder
    (10) node displacement recorder
    (11) beam force recorder
    (12) column force recorder
    (13) gravity dead load
    (14) gravity live load
    (15) earthquake load
    (16) gravity and earthquake loads combination
    (17) copy baseline .tcl files
    (18) run OpenSees.exe
    """
```

In [41]:
from elastic_analysis import ElasticAnalysis

# Perform EigenValue Analysis only to obtain the period
_ = ElasticAnalysis(building_1, for_drift_only=False, for_period_only=True)

#### write_nodes

```python
def write_nodes(self, building):
    # Create a .tcl file and write the node information
    with open('DefineNodes2DModel.tcl', 'w') as tclfile:
        tclfile.write("# This file will be used to define all nodes \n")  # Introduce the file usage
        tclfile.write("# Units: inch \n\n\n")  # Explain the units
        tclfile.write("# Set bay width and story height \n")
        tclfile.write("set\tBayWidth\t[expr %.2f*12]; \n" % (building.geometry['X bay width']))
        tclfile.write("set\tFirstStory\t[expr %.2f*12]; \n" % (building.geometry['first story height']))
        tclfile.write("set\tTypicalStory\t[expr %.2f*12]; \n\n\n" % (building.geometry['typical story height']))
        # Write the nodes at beam column intersection points
        tclfile.write("# Define nodes at corner of frames \n")
        for i in range(1, building.geometry['number of story']+2):  # i is floor level number
            tclfile.write("# Level %i \n" % i)
            for j in range(1, building.geometry['number of X bay']+2):  # j is column label
                tclfile.write("node\t%i%i%i" % (j, i, 1))  # Node label
                tclfile.write("\t[expr %i*$BayWidth]" % (j - 1))  # X coordinate
                if i <= 2:
                    tclfile.write("\t[expr %i*$FirstStory];" % (i - 1))  # Y coordinate
                    tclfile.write("\t # Column #%i \n" % j)  # Comments to explain the column label
                else:
                    tclfile.write("\t[expr 1*FirstStory+TypicalStory];" % (i - 2))
                    tclfile.write("\t # Column #%i \n" % j)
            tclfile.write("\n")
        tclfile.write("# puts \"Nodes at frame corner defined\" \n\n")
        # Write the nodes for leaning column
        tclfile.write("# Define nodes for leaning column \n")
        for i in range(1, building.geometry['number of story']+2):
            tclfile.write("node\t%i%i" % (building.geometry['number of X bay']+2, i))  # Node label
            tclfile.write("\t[expr %i*$BayWidth]" % (building.geometry['number of X bay']+1))  # X coordinate
            if i <= 2:
                tclfile.write("\t[expr %i*$FirstStory]; " % (i-1))  # Y coordinate
                tclfile.write("\t# Level %i\n" % i)  # Comments to explain floor level
            else:
                tclfile.write("\t[expr 1*FirstStory+TypicalStory];" % (i-2))
                tclfile.write("\t# Level %i\n" % i)
        tclfile.write("\n")
        tclfile.write("# puts \"Nodes for leaning column defined\" \n\n")
        # Write the extra nodes for leaning column springs
        tclfile.write("# Define extra nodes needed to define leaning column springs \n")
        for i in range(2, building.geometry['number of story']+2):
            # The node below floor level
            tclfile.write("node\t%i%i%i" % (building.geometry['number of X bay']+2, i, 2))  # Node label
            tclfile.write("\t[expr %i*$BayWidth]" % (building.geometry['number of X bay'] + 1))  # X coordinate
            tclfile.write("\t[expr 1*FirstStory+TypicalStory];" % (i-2))  # Y coordinate
            tclfile.write("\t# Node below floor level %i\n" % i)
            # If it's top story, node above roof is not needed
            # because no leaning column above roof
            if i < building.geometry['number of story']+1:
                # The node above floor level
                tclfile.write("node\t%i%i%i" % (building.geometry['number of X bay']+2, i, 4))  # Nodel label
                tclfile.write("\t[expr %i*$BayWidth]" % (building.geometry['number of X bay']+1))  # X coordinate
                tclfile.write("\t[expr 1*FirstStory+TypicalStory];" % (i-2))  # Y coordinate
                tclfile.write("\t# Node above floor level %i\n" % i)
            else:
                pass
        tclfile.write("\n")
        tclfile.write("# puts \"Extra nodes for leaning column springs defined\"\n")
```

In [46]:
f = open('DefineNodes2DModel.tcl', 'r')
file_contents = f.read()
print (file_contents)
f.close()

# This file will be used to define all nodes 
# Units: inch 


# Set bay width and story height 
set	BayWidth	[expr 30.00*12]; 
set	FirstStory	[expr 13.00*12]; 
set	TypicalStory	[expr 13.00*12]; 


# Define nodes at corner of frames 
# Level 1 
node	111	[expr 0*$BayWidth]	[expr 0*$FirstStory];	 # Column #1 
node	211	[expr 1*$BayWidth]	[expr 0*$FirstStory];	 # Column #2 
node	311	[expr 2*$BayWidth]	[expr 0*$FirstStory];	 # Column #3 
node	411	[expr 3*$BayWidth]	[expr 0*$FirstStory];	 # Column #4 
node	511	[expr 4*$BayWidth]	[expr 0*$FirstStory];	 # Column #5 

# Level 2 
node	121	[expr 0*$BayWidth]	[expr 1*$FirstStory];	 # Column #1 
node	221	[expr 1*$BayWidth]	[expr 1*$FirstStory];	 # Column #2 
node	321	[expr 2*$BayWidth]	[expr 1*$FirstStory];	 # Column #3 
node	421	[expr 3*$BayWidth]	[expr 1*$FirstStory];	 # Column #4 
node	521	[expr 4*$BayWidth]	[expr 1*$FirstStory];	 # Column #5 

# Level 3 
node	131	[expr 0*$BayWidth]	[expr 1*$FirstStory+1*$TypicalStory];	 # Column #1 
node	231	[e

#### write_fixities

```python
def write_fixities(self, building):
    # Create a .tcl file to write boundary for the model
    with open('DefineFixities2DModel.tcl', 'w') as tclfile:
        tclfile.write("# This file will be used to define the fixity at all column bases \n\n\n")
        tclfile.write("# Defining fixity at column base \n")
        for j in range(1, building.geometry['number of X bay']+2):
            tclfile.write("fix\t%i%i%i\t1\t1\t1; \n" % (j, 1, 1))
        # Leaning column base
        tclfile.write("fix\t%i%i\t1\t1\t0; \n\n" % (building.geometry['number of X bay']+2, 1))
        tclfile.write("# puts \"All column base fixities have been defined\"")
```

In [48]:
building_1.geometry

{'number of story': 3,
 'number of X bay': 4,
 'number of Z bay': 4,
 'first story height': 13,
 'typical story height': 13,
 'X bay width': 30,
 'Z bay width': 30,
 'number of X LFRS': 2,
 'number of Z LFRS': 2,
 'floor height': array([[ 0.],
        [13.],
        [26.],
        [39.]])}

In [50]:
for j in range(1, building_1.geometry['number of X bay']+2):
    print("fix\t%i%i%i\t1\t1\t1; \n" % (j, 1, 1))

fix	111	1	1	1; 

fix	211	1	1	1; 

fix	311	1	1	1; 

fix	411	1	1	1; 

fix	511	1	1	1; 



In [47]:
f = open('DefineFixities2DModel.tcl', 'r')
file_contents = f.read()
print (file_contents)
f.close()

# This file will be used to define the fixity at all column bases 


# Defining fixity at column base 
fix	111	1	1	1; 
fix	211	1	1	1; 
fix	311	1	1	1; 
fix	411	1	1	1; 
fix	511	1	1	1; 
fix	61	1	1	0; 

# puts "All column base fixities have been defined"


#### write_floor_constraint

```python
def write_floor_constraint(self, building):
    # Create a .tcl file to write floor constrain, i.e., equal DOF
    with open('DefineFloorConstraint2DModel.tcl', 'w') as tclfile:
        tclfile.write("# This file will be used to define floor constraint \n\n")
        tclfile.write("set\tConstrainDOF\t1;\t# Nodes at same floor level have identical lateral displacement \n\n")
        # Constraint starts from floor level 2
        for i in range(2, building.geometry['number of story']+2):
            tclfile.write("# Level %i \n" % i)
            for j in range(2, building.geometry['number of X bay']+2):
                tclfile.write("equalDOF\t%i%i%i\t%i%i%i\t$ConstrainDOF;" % (1, i, 1, j, i, 1))
                tclfile.write("\t# Pier 1 to Pier %i\n" % j)
            # Include the leaning column nodes to floor constrain
            tclfile.write("equalDOF\t%i%i%i\t%i%i\t$ConstrainDOF;"
                          % (1, i, 1, building.geometry['number of X bay']+2, i))
            tclfile.write("\t# Pier 1 to Leaning column\n\n")
        tclfile.write("# puts \"Floor constraint defined\"")
```

In [48]:
building_1.geometry

{'number of story': 3,
 'number of X bay': 4,
 'number of Z bay': 4,
 'first story height': 13,
 'typical story height': 13,
 'X bay width': 30,
 'Z bay width': 30,
 'number of X LFRS': 2,
 'number of Z LFRS': 2,
 'floor height': array([[ 0.],
        [13.],
        [26.],
        [39.]])}

In [51]:
for i in range(2, building_1.geometry['number of story']+2):
    print("# Level %i \n" % i)
    for j in range(2, building_1.geometry['number of X bay']+2):
        print("equalDOF\t%i%i%i\t%i%i%i\t$ConstrainDOF;" % (1, i, 1, j, i, 1))
        print("\t# Pier 1 to Pier %i\n" % j)

# Level 2 

equalDOF	121	221	$ConstrainDOF;
	# Pier 1 to Pier 2

equalDOF	121	321	$ConstrainDOF;
	# Pier 1 to Pier 3

equalDOF	121	421	$ConstrainDOF;
	# Pier 1 to Pier 4

equalDOF	121	521	$ConstrainDOF;
	# Pier 1 to Pier 5

# Level 3 

equalDOF	131	231	$ConstrainDOF;
	# Pier 1 to Pier 2

equalDOF	131	331	$ConstrainDOF;
	# Pier 1 to Pier 3

equalDOF	131	431	$ConstrainDOF;
	# Pier 1 to Pier 4

equalDOF	131	531	$ConstrainDOF;
	# Pier 1 to Pier 5

# Level 4 

equalDOF	141	241	$ConstrainDOF;
	# Pier 1 to Pier 2

equalDOF	141	341	$ConstrainDOF;
	# Pier 1 to Pier 3

equalDOF	141	441	$ConstrainDOF;
	# Pier 1 to Pier 4

equalDOF	141	541	$ConstrainDOF;
	# Pier 1 to Pier 5



In [52]:
f = open('DefineFloorConstraint2DModel.tcl', 'r')
file_contents = f.read()
print (file_contents)
f.close()

# This file will be used to define floor constraint 

set	ConstrainDOF	1;	# Nodes at same floor level have identical lateral displacement 

# Level 2 
equalDOF	121	221	$ConstrainDOF;	# Pier 1 to Pier 2
equalDOF	121	321	$ConstrainDOF;	# Pier 1 to Pier 3
equalDOF	121	421	$ConstrainDOF;	# Pier 1 to Pier 4
equalDOF	121	521	$ConstrainDOF;	# Pier 1 to Pier 5
equalDOF	121	62	$ConstrainDOF;	# Pier 1 to Leaning column

# Level 3 
equalDOF	131	231	$ConstrainDOF;	# Pier 1 to Pier 2
equalDOF	131	331	$ConstrainDOF;	# Pier 1 to Pier 3
equalDOF	131	431	$ConstrainDOF;	# Pier 1 to Pier 4
equalDOF	131	531	$ConstrainDOF;	# Pier 1 to Pier 5
equalDOF	131	63	$ConstrainDOF;	# Pier 1 to Leaning column

# Level 4 
equalDOF	141	241	$ConstrainDOF;	# Pier 1 to Pier 2
equalDOF	141	341	$ConstrainDOF;	# Pier 1 to Pier 3
equalDOF	141	441	$ConstrainDOF;	# Pier 1 to Pier 4
equalDOF	141	541	$ConstrainDOF;	# Pier 1 to Pier 5
equalDOF	141	64	$ConstrainDOF;	# Pier 1 to Leaning column

# puts "Floor constraint defined"


#### write_beam

```python
def write_beam(self, building):
    # Create a .tcl file to write beam elements
    with open('DefineBeams2DModel.tcl', 'w') as tclfile:
        tclfile.write("# This file will be used to define beam elements \n\n\n")
        tclfile.write("# Define beam section sizes \n")
        for i in range(2, building.geometry['number of story']+2):
            tclfile.write("set\tBeamLevel%i\t[SectionProperty %s]; \n" % (i, building.member_size['beam'][i-2]))
        tclfile.write("\n\n# Define beams \n")
        for i in range(2, building.geometry['number of story']+2):
            tclfile.write("# Level %i\n" % i)
            # Beam elements in frame
            for j in range(1, building.geometry['number of X bay']+1):
                tclfile.write("element\telasticBeamColumn")  # elastic beam-column command
                tclfile.write("\t%i%i%i%i%i%i%i" % (2, j, i, 1, j+1, i, 1))  # Beam element tag
                tclfile.write("\t%i%i%i" % (j, i, 1))  # Starting node
                tclfile.write("\t%i%i%i" % (j+1, i, 1))  # Ending node
                tclfile.write("\t[lindex $BeamLevel%i 2]" % i)  # Area of beam section
                tclfile.write("\t$Es")  # Young's modulus of steel material
                tclfile.write("\t[lindex $BeamLevel%i 6]" % i)  # Moment of inertia of beam section
                tclfile.write("\t$LinearTransf; \n")  # Geometric transformation
            # Beam elements connection frame and leaning column
            tclfile.write("element\ttruss")  # elastic beam-column command
            tclfile.write("\t%i%i%i%i%i%i" % (2, building.geometry['number of X bay']+1, i, 1,
                                              building.geometry['number of X bay']+2, i))
            tclfile.write("\t%i%i%i" % (building.geometry['number of X bay']+1, i, 1))  # Starting node in frame
            tclfile.write("\t%i%i" % (building.geometry['number of X bay']+2, i))  # Ending node in leaning column
            tclfile.write("\t$AreaRigid\t$TrussMatID; \n")  # Large area and truss element material
            tclfile.write("\n")
        tclfile.write("# puts \"Beams defined\"")
```

In [55]:
for i in range(2, building_1.geometry['number of story']+2):
    print("set\tBeamLevel%i\t[SectionProperty %s]; \n" % (i, building_1.member_size['beam'][i-2]))
print("\n\n# Define beams \n")
for i in range(2, building_1.geometry['number of story']+2):
    print("# Level %i\n" % i)
    # Beam elements in frame
    for j in range(1, building_1.geometry['number of X bay']+1):
        print("element\telasticBeamColumn")  # elastic beam-column command
        print("\t%i%i%i%i%i%i%i" % (2, j, i, 1, j+1, i, 1))  # Beam element tag
        print("\t%i%i%i" % (j, i, 1))  # Starting node
        print("\t%i%i%i" % (j+1, i, 1))  # Ending node
        print("\t[lindex $BeamLevel%i 2]" % i)  # Area of beam section
        print("\t$Es")  # Young's modulus of steel material
        print("\t[lindex $BeamLevel%i 6]" % i)  # Moment of inertia of beam section
        print("\t$LinearTransf; \n")  # Geometric transformation

set	BeamLevel2	[SectionProperty W33X263]; 

set	BeamLevel3	[SectionProperty W33X263]; 

set	BeamLevel4	[SectionProperty W33X263]; 



# Define beams 

# Level 2

element	elasticBeamColumn
	2121221
	121
	221
	[lindex $BeamLevel2 2]
	$Es
	[lindex $BeamLevel2 6]
	$LinearTransf; 

element	elasticBeamColumn
	2221321
	221
	321
	[lindex $BeamLevel2 2]
	$Es
	[lindex $BeamLevel2 6]
	$LinearTransf; 

element	elasticBeamColumn
	2321421
	321
	421
	[lindex $BeamLevel2 2]
	$Es
	[lindex $BeamLevel2 6]
	$LinearTransf; 

element	elasticBeamColumn
	2421521
	421
	521
	[lindex $BeamLevel2 2]
	$Es
	[lindex $BeamLevel2 6]
	$LinearTransf; 

# Level 3

element	elasticBeamColumn
	2131231
	131
	231
	[lindex $BeamLevel3 2]
	$Es
	[lindex $BeamLevel3 6]
	$LinearTransf; 

element	elasticBeamColumn
	2231331
	231
	331
	[lindex $BeamLevel3 2]
	$Es
	[lindex $BeamLevel3 6]
	$LinearTransf; 

element	elasticBeamColumn
	2331431
	331
	431
	[lindex $BeamLevel3 2]
	$Es
	[lindex $BeamLevel3 6]
	$LinearTransf; 

element	elastic

In [53]:
f = open('DefineBeams2DModel.tcl', 'r')
file_contents = f.read()
print (file_contents)
f.close()

# This file will be used to define beam elements 


# Define beam section sizes 
set	BeamLevel2	[SectionProperty W33X263]; 
set	BeamLevel3	[SectionProperty W33X263]; 
set	BeamLevel4	[SectionProperty W33X263]; 


# Define beams 
# Level 2
element	elasticBeamColumn	2121221	121	221	[lindex $BeamLevel2 2]	$Es	[lindex $BeamLevel2 6]	$LinearTransf; 
element	elasticBeamColumn	2221321	221	321	[lindex $BeamLevel2 2]	$Es	[lindex $BeamLevel2 6]	$LinearTransf; 
element	elasticBeamColumn	2321421	321	421	[lindex $BeamLevel2 2]	$Es	[lindex $BeamLevel2 6]	$LinearTransf; 
element	elasticBeamColumn	2421521	421	521	[lindex $BeamLevel2 2]	$Es	[lindex $BeamLevel2 6]	$LinearTransf; 
element	truss	252162	521	62	$AreaRigid	$TrussMatID; 

# Level 3
element	elasticBeamColumn	2131231	131	231	[lindex $BeamLevel3 2]	$Es	[lindex $BeamLevel3 6]	$LinearTransf; 
element	elasticBeamColumn	2231331	231	331	[lindex $BeamLevel3 2]	$Es	[lindex $BeamLevel3 6]	$LinearTransf; 
element	elasticBeamColumn	2331431	331	431	[lindex 

### global_variables.py

#### SteelMaterial

https://github.com/shishitao/AutoSDAPlatform/blob/master/steel_material.py

```python
class SteelMaterial(object):
    """
    This class is used to define the steel material.
    It includes the following physical quantities:
    (1) Yield stress (Fy)
    (2) Ultimate stress (Fu)
    (3) Young's modulus (E)
    (4) Ry value
    """

    def __init__(self, yield_stress=50, ultimate_stress=65, elastic_modulus=29000, Ry_value=1.1):
        """
        :param yield_stress: Fy of steel material, default value is 50 ksi
        :param elastic_modulus: E of steel material, default value is 29000 ksi
        """
        self.Fy = yield_stress
        self.Fu = ultimate_stress
        self.E = elastic_modulus
        self.Ry = Ry_value
```

In [17]:
from steel_material import SteelMaterial

# Define the current utilized steel type:
steel = SteelMaterial(yield_stress=50, ultimate_stress=65, elastic_modulus=29000, Ry_value=1.1)  # Unit: ksi

In [18]:
steel.Fy

50

In [19]:
steel.Fu

65

In [20]:
steel.E

29000

In [21]:
steel.Ry

1.1

#### base_directory
```python
# Define path to where ElasticAnalysis tool base directory
base_directory = pathlib.Path(os.getcwd())
```

In [22]:
import os
import pathlib

pathlib.Path(os.getcwd())

WindowsPath('G:/My Drive/Reference/GitHub/AutoSDAPlatform/BuildingData/Building_0')

In [23]:
os.getcwd() # pathlib.Path(os.getcwd()) vs os.getcwd()

'G:\\My Drive\\Reference\\GitHub\\AutoSDAPlatform\\BuildingData\\Building_0'

### help_functions.py

In [24]:
import numpy as np
import re
import sys

from global_variables import SECTION_DATABASE

#### 

```python

```

### seismic_design.py

https://github.com/shishitao/AutoSDAPlatform/blob/master/seismic_design.py

#### seismic_force

```python
# Create an instance using "Building" class
building_1 = Building(building_id, base_directory)
# Perform EigenValue Analysis only to obtain the period
_ = ElasticAnalysis(building_1, for_drift_only=False, for_period_only=True)
building_1.read_modal_period()
# Compute the seismic story forces based on modal period and CuTa
building_1.compute_seismic_force()
```

In [56]:
# Perform EigenValue Analysis only to obtain the period
_ = ElasticAnalysis(building_1, for_drift_only=False, for_period_only=True)
building_1.read_modal_period()
# Compute the seismic story forces based on modal period and CuTa
building_1.compute_seismic_force()

In [58]:
building_1.seismic_force_for_strength 

{'lateral story force': 0    161.780675
 1    350.985815
 2    552.140063
 Name: floor weight, dtype: float64,
 'story shear': array([[1064.90655257],
        [ 903.12587792],
        [ 552.14006327]]),
 'base shear': 1064.906552570187,
 'Cs': 0.15507595057087328}

In [59]:
building_1.seismic_force_for_drift  

{'lateral story force': 0    161.780675
 1    350.985815
 2    552.140063
 Name: floor weight, dtype: float64,
 'story shear': array([[1064.90655257],
        [ 903.12587792],
        [ 552.14006327]]),
 'base shear': 1064.906552570187,
 'Cs': 0.15507595057087328}